"""todos table

Revision ID: 5c4725f70af3
Revises: 230ebe80b2b3
Create Date: 2018-01-27 19:29:00.472032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c4725f70af3'
down_revision = '230ebe80b2b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_date'), 'todo', ['date'], unique=False)
    op.create_index(op.f('ix_todo_due_date'), 'todo', ['due_date'], unique=False)
    op.create_index(op.f('ix_todo_timestamp'), 'todo', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todo_timestamp'), table_name='todo')
    op.drop_index(op.f('ix_todo_due_date'), table_name='todo')
    op.drop_index(op.f('ix_todo_date'), table_name='todo')
    op.drop_table('todo')
    # ### end Alembic commands ###
